### ISSUE TITLE
Error MSB6006: "plutil" exited with code 1. (MSB6006)

### ISSUE THREAD

**Issue by alexrainman** [mrward/monodevelop-template-creator-addin#2] opened 2017-12-13 06:20 UTC
I get this error after creating a new project from template. The original project works.

When i double-click the error it takes me to this in Xamarin.iOS.Common.targets file:

```xml
<OptimizePropertyList
			SessionId="$(BuildSessionId)"
			Condition="'$(IsMacEnabled)' == 'true'"
			ToolExe="$(PlUtilExe)"
			ToolPath="$(PlUtilPath)"
			Input="%(_PropertyList.Identity)"
			Output="$(DeviceSpecificIntermediateOutputPath)optimized\%(_PropertyList.LogicalName)">
		</OptimizePropertyList>
```

**Comment by mrward** [comment] 2017-12-13 09:21
Can you provide the template?

The error message does not indicate to me where the problem is. Is there more error information if you do a diagnostic build?

I would guess that maybe a file is being formatted on new project creation and plutil does not like it. So I would look at a diff between the template and the created project to see what has changed.

**Comment by alexrainman** [comment] 2017-12-13 13:15
Found the problem. There's a file that is on binary format that is converted this way:

<img width="960" alt="screen shot 2017-12-13 at 7 13 36 am" src="https://user-images.githubusercontent.com/3793554/33940603-384fa192-dfd5-11e7-9c28-25a69590c765.png">

It seems you builder doesn't like it. It contains the bundle name so maybe your builder is trying to write it and the file gets corrupted.

**Comment by mrward** [comment] 2017-12-13 13:26
So the AppConnect.plist is the one with the problem? .plist files I believe are xml files so the default formatter would be trying to reformat it using the xml formatting rules configured in VS Mac.

I think the fix here would be a way to specify files that should not be formatted by setting some name-value pair in the tags section of the template.json file. I added support for the same basic feature in VS Mac recently, not yet released, where you could specify a filename or a wildcard to avoid formatting certain files.

**Comment by alexrainman** [comment] 2017-12-13 13:35
When are you planning to release? This extension is great. Very good job.

**Comment by mrward** [comment] 2017-12-13 22:39
I have a fix for this now on a separate branch. I want to do some more testing before producing a new build of the extension and publishing it.

**Comment by alexrainman** [comment] 2017-12-13 22:49
I removed that file for now. Will update as soon as you release. Thanks a lot

**Closed as completed** 2017-12-19 11:22 UTC

**Comment by mrward** [comment] 2017-12-19 11:27
New [0.2 release](https://github.com/mrward/monodevelop-template-creator-addin/releases/download/0.2/MonoDevelop.TemplateCreator_0.2.mpack) of the template creator addin is now available.

This supports excluding files from being formatted. You can do this by adding a vsmac-file-format-exclude tag to the template.json. This tag will also be created if a file format exclude is specified when creating the template in the Template Information dialog.

```
	"tags": {
		"language": "C#",
		"type": "project",
		"vsmac-category": "other/net/general",
		"vsmac-file-format-exclude": "*.xml"
	},
```
